const SIGNUP_DATA_SUCCESS = 'SIGNUP_DATA_SUCCESS';
const REMOVE_DATA_SUCCESS = 'REMOVE_DATA_SUCCESS';
const EDIT_DATA_SUCCESS = 'EDIT_DATA_SUCCESS';

export { SIGNUP_DATA_SUCCESS, REMOVE_DATA_SUCCESS, EDIT_DATA_SUCCESS };
